### ISSUE TITLE
Unable to --add-to-schedule

### ISSUE THREAD

**Issue by theinflexibleyogi** [tableau/tableau-data-acceleration-client#4]
I'm able to run all the commands except --add-to-schedule. Am I missing something ? Please help, thanks! 

%run accelerate_workbooks.py --add-to-schedule "SCHEDULE" "PRODUCTION/Non-Realtime Dashboard/performance_d"
**ERROR:root:File `'accelerate_workbooks.py\u202f--add-to-schedule.py'` not found.**

The rest works as below:
Workbook Acceleration is enabled for the following workbooks 
+--------------+-----------------------------------------------------------------------+-------------+---------------------------+--------------------------+
| Site         | Project/Workbook                                                      | Status      | Last Updated              | Task Running Time (Secs) |
+--------------+-----------------------------------------------------------------------+-------------+---------------------------+--------------------------+
| DolfinWallet | PRODUCTION/Non-Realtime Dashboard/=activeness          | accelerated | 2020-10-15 15:53:53+07:00 |                    124.0 |
| DolfinWallet | PRODUCTION/Non-Realtime Dashboard/=performance_d           | accelerated | 2020-10-15 15:21:48+07:00 |                     28.0 |
| DolfinWallet | PRODUCTION/Non-Realtime Dashboard/=kpi               | accelerated | 2020-10-15 15:19:03+07:00 |                     12.0 |
| DolfinWallet | PRODUCTION/Non-Realtime Dashboard/dolfin_transaction                  | accelerated | 2020-10-15 15:53:39+07:00 |                      9.0 |
| DolfinWallet | PRODUCTION/Non-Realtime Dashboard/segment | accelerated | 2020-10-15 15:22:06+07:00 |                      8.0 |
+--------------+-----------------------------------------------------------------------+-------------+---------------------------+--------------------------+

Scheduled Tasks for Workbook Acceleration 
+-----------------------------------------------------------------------+----------+-------------+
| Project/Workbook                                                      | Schedule | Next Run At |
+-----------------------------------------------------------------------+----------+-------------+
| PRODUCTION/Non-Realtime Dashboard/segment | *        |             |
| PRODUCTION/Non-Realtime Dashboard/performance_d           | *        |             |
| PRODUCTION/Non-Realtime Dashboard/kpi               | *        |             |
| PRODUCTION/Non-Realtime Dashboard/activeness          | *        |             |
| PRODUCTION/Non-Realtime Dashboard/transaction                  | *        |             |
+-----------------------------------------------------------------------+----------+-------------+
*The Workbook Acceleration views for these workbooks will be updated when they are published, or when their extract is refreshed.

**Comment by guodah** [comment]
Seems the command is not formatted right as "accelerate_workbooks.py\u202f--add-to-schedule.py" is considered as a python file name. You could split the command in to multiple lines like

run accelerate_workbooks.py  \
     --add-to-schedule   \
     "SCHEDULE"  \ 
     "PRODUCTION/Non-Realtime Dashboard/performance_d"
